Fixes#11 [No Prefix Option]
MattieBelt/strapi-hook-algolia pull request #12
Opened 2021-09-20 17:15 UTC by anouarkacem

### Default Prefix
Changed default prefix to `false`

2021-09-22 10:57 UTC, MattieBelt requested changes
Hey @anouarkacem,

Thanks for submitting this PR, I do think some changes are required before it can be merged.

Let me know if you have any question about the review.

2021-09-22 10:57 UTC, MattieBelt commented on lib/index.js
> -      prefix: strapi.config.environment,
I don't think `false` should be the default value here. I think it is a best practice to use environments in the index names.
So no need to change it here and in the [README.md](https://github.com/MattieBelt/strapi-hook-algolia/blob/86d0f1e4d610c2959e4a541526fac176981e1ee7/README.md).

2021-09-22 10:57 UTC, MattieBelt commented on lib/index.js
> +        const index = (prefix && `${prefix}_${indexName}`) || `${indexName}`;
Template string here is redundant.

```suggestion
        const index = (prefix && `${prefix}_${indexName}`) || indexName;
```

As well as `prefix` should be strictly equal to `false`.
Something like this
```js
return client.initIndex((prefix === false) ? indexName : `${prefix}_${indexName}`);
```

2021-09-22 10:57 UTC, MattieBelt commented on README.md
> -        prefix: 'my_own_prefix'   // default: Strapi environment (strapi.config.environment)
The default value should remain `strapi.config.environment`, but the possibility to disable the prefix with `prefix: false` should be documented somewhere in the README.md.

2021-09-22 16:06 UTC, anouarkacem commented
hey @MattieBelt 
Yes agree with you, thank you for the review I made the requested changes

2021-09-23 12:48 UTC, MattieBelt requested changes
The `index.js` looks fine, just a small change on the docs.

2021-09-23 12:48 UTC, MattieBelt commented on README.md
> +- No prefix: false (index)
I think something like this explains the prefix usage better:

```suggestion
### Prefix
The default prefix uses `strapi.config.environment`, resulting in for example: 'development_post'.
A custom prefix can be configured with the `prefix` option in the hook config.   
If you don't want to use any prefix at all, you can configure it with: `prefix: false`.
```

2021-09-24 08:04 UTC, MattieBelt approved these changes

2021-09-24 08:04 UTC, MattieBelt commented
LGTM, thanks again!

2021-09-24 08:05 UTC, merged

2021-09-24 08:12 UTC, anouarkacem commented
Great, thank you too !